[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
solc_version = "0.8.16"
auto_detect_solc = false
optimizer = true
optimizer_runs = 200
ffi = true

[profile.ci]
runs = 1000

# See more config options https://github.com/foundry-rs/foundry/tree/master/config